<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <!-- Required to build Windows-targeted projects on non-Windows CI -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>SharpSIP</AssemblyName>
    <RootNamespace>SharpSIP</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="6.2.3" />
    <PackageReference Include="SIPSorceryMedia.Windows" Version="6.0.4" />
  </ItemGroup>

</Project>
